export const SAMPLE_VOCAB = [
  { word: 'deteriorate', type: 'v', meaning: 'xuống cấp, xấu đi', phonetic: '/dɪˈtɪəriəreɪt/', example: 'Air quality has deteriorated significantly.', synonyms: ['decline', 'worsen'], topic: 'environment' },
  { word: 'sustainable', type: 'adj', meaning: 'bền vững', phonetic: '/səˈsteɪnəbl/', example: 'We need sustainable energy sources.', synonyms: ['viable', 'long-term'], topic: 'environment' },
  { word: 'curriculum', type: 'n', meaning: 'chương trình giảng dạy', phonetic: '/kəˈrɪkjʊləm/', example: 'The school updated its curriculum.', synonyms: ['syllabus', 'program'], topic: 'education' },
  { word: 'innovative', type: 'adj', meaning: 'sáng tạo, đổi mới', phonetic: '/ˈɪnəveɪtɪv/', example: 'Innovative teaching methods improve learning.', synonyms: ['creative', 'groundbreaking'], topic: 'education' },
  { word: 'ubiquitous', type: 'adj', meaning: 'có mặt khắp nơi', phonetic: '/juːˈbɪkwɪtəs/', example: 'Smartphones have become ubiquitous.', synonyms: ['omnipresent', 'widespread'], topic: 'technology' },
  { word: 'exacerbate', type: 'v', meaning: 'làm trầm trọng thêm', phonetic: '/ɪɡˈzæsərbeɪt/', example: 'Pollution exacerbates health problems.', synonyms: ['aggravate', 'worsen'], topic: 'health' },
  { word: 'phenomenon', type: 'n', meaning: 'hiện tượng', phonetic: '/fəˈnɒmɪnən/', example: 'Global warming is a well-documented phenomenon.', synonyms: ['occurrence', 'event'], topic: 'environment' },
  { word: 'predominantly', type: 'adv', meaning: 'chủ yếu, phần lớn', phonetic: '/prɪˈdɒmɪnəntli/', example: 'The workforce is predominantly young.', synonyms: ['mainly', 'mostly'], topic: 'society' },
  { word: 'fluctuate', type: 'v', meaning: 'dao động, biến đổi', phonetic: '/ˈflʌktʃueɪt/', example: 'Prices fluctuate throughout the year.', synonyms: ['vary', 'oscillate'], topic: 'work' },
  { word: 'infrastructure', type: 'n', meaning: 'cơ sở hạ tầng', phonetic: '/ˈɪnfrəstrʌktʃər/', example: 'The government invested in infrastructure.', synonyms: ['framework', 'foundation'], topic: 'society' },
  { word: 'autonomous', type: 'adj', meaning: 'tự chủ, tự trị', phonetic: '/ɔːˈtɒnəməs/', example: 'Autonomous vehicles are being tested.', synonyms: ['independent', 'self-governing'], topic: 'technology' },
  { word: 'alleviate', type: 'v', meaning: 'giảm bớt, xoa dịu', phonetic: '/əˈliːvieɪt/', example: 'Medicine can alleviate pain.', synonyms: ['relieve', 'ease'], topic: 'health' },
  { word: 'compelling', type: 'adj', meaning: 'thuyết phục, hấp dẫn', phonetic: '/kəmˈpelɪŋ/', example: 'She made a compelling argument.', synonyms: ['convincing', 'persuasive'], topic: 'other' },
  { word: 'disparity', type: 'n', meaning: 'sự chênh lệch', phonetic: '/dɪˈspærəti/', example: 'Income disparity is a growing concern.', synonyms: ['inequality', 'gap'], topic: 'society' },
  { word: 'proficiency', type: 'n', meaning: 'sự thành thạo', phonetic: '/prəˈfɪʃənsi/', example: 'Language proficiency is essential.', synonyms: ['competence', 'expertise'], topic: 'education' },
  { word: 'mitigate', type: 'v', meaning: 'giảm thiểu', phonetic: '/ˈmɪtɪɡeɪt/', example: 'Trees help mitigate climate change.', synonyms: ['reduce', 'lessen'], topic: 'environment' },
  { word: 'unprecedented', type: 'adj', meaning: 'chưa từng có tiền lệ', phonetic: '/ʌnˈpresɪdentɪd/', example: 'The pandemic caused unprecedented disruption.', synonyms: ['unparalleled', 'unheard-of'], topic: 'society' },
  { word: 'sedentary', type: 'adj', meaning: 'ít vận động', phonetic: '/ˈsedəntri/', example: 'A sedentary lifestyle leads to health issues.', synonyms: ['inactive', 'stationary'], topic: 'health' },
  { word: 'versatile', type: 'adj', meaning: 'đa năng, linh hoạt', phonetic: '/ˈvɜːsətaɪl/', example: 'She is a versatile employee.', synonyms: ['adaptable', 'flexible'], topic: 'work' },
  { word: 'proliferation', type: 'n', meaning: 'sự gia tăng nhanh', phonetic: '/prəˌlɪfəˈreɪʃən/', example: 'The proliferation of social media changed communication.', synonyms: ['spread', 'expansion'], topic: 'technology' },
  { word: 'detrimental', type: 'adj', meaning: 'có hại', phonetic: '/ˌdetrɪˈmentl/', example: 'Smoking is detrimental to health.', synonyms: ['harmful', 'damaging'], topic: 'health' },
  { word: 'incentive', type: 'n', meaning: 'động lực, ưu đãi', phonetic: '/ɪnˈsentɪv/', example: 'Tax incentives encourage investment.', synonyms: ['motivation', 'stimulus'], topic: 'work' },
  { word: 'eradicate', type: 'v', meaning: 'xóa bỏ, loại trừ', phonetic: '/ɪˈrædɪkeɪt/', example: 'Efforts to eradicate poverty continue.', synonyms: ['eliminate', 'abolish'], topic: 'society' },
  { word: 'cognitive', type: 'adj', meaning: 'thuộc nhận thức', phonetic: '/ˈkɒɡnətɪv/', example: 'Reading improves cognitive abilities.', synonyms: ['mental', 'intellectual'], topic: 'education' },
  { word: 'biodiversity', type: 'n', meaning: 'đa dạng sinh học', phonetic: '/ˌbaɪəʊdaɪˈvɜːsəti/', example: 'Deforestation threatens biodiversity.', synonyms: ['ecological variety'], topic: 'environment' },
]

export const QUOTES = [
  '"The secret of getting ahead is getting started." — Mark Twain',
  '"A different language is a different vision of life." — Federico Fellini',
  '"One language sets you in a corridor for life. Two languages open every door along the way." — Frank Smith',
  '"The limits of my language mean the limits of my world." — Ludwig Wittgenstein',
  '"Learning is not attained by chance, it must be sought for with ardor." — Abigail Adams',
  '"Success is the sum of small efforts, repeated day in and day out." — Robert Collier',
  '"Don\'t watch the clock; do what it does. Keep going." — Sam Levenson',
  '"You don\'t have to be great to start, but you have to start to be great." — Zig Ziglar',
  '"Consistency is what transforms average into excellence."',
  '"Every expert was once a beginner."',
]
